#pragma once

#include <devioctl.h>

// {7A50A0E8-289F-4A72-9BC4-11A40FC1A63C}
static const GUID GUID_DEVINTERFACE_CODEX_MICRO_CONTROL =
{ 0x7a50a0e8, 0x289f, 0x4a72, { 0x9b, 0xc4, 0x11, 0xa4, 0x0f, 0xc1, 0xa6, 0x3c } };

#define CODEX_MICRO_REPORT_ID 6u
#define CODEX_MICRO_REPORT_BYTES 64u

#define IOCTL_CODEX_GET_OUTPUT_REPORT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_CODEX_SEND_INPUT_REPORT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#define IOCTL_CODEX_GET_STATS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)

#pragma pack(push, 1)

typedef struct _CODEX_REPORT_RECORD {
    ULONGLONG Sequence;
    ULONG Length;
    UCHAR Report[CODEX_MICRO_REPORT_BYTES];
} CODEX_REPORT_RECORD, *PCODEX_REPORT_RECORD;

typedef struct _CODEX_DRIVER_STATS {
    ULONGLONG OutputReportsReceived;
    ULONGLONG OutputReportsDropped;
    ULONGLONG InputReportsSubmitted;
    ULONGLONG InvalidReportsRejected;
    ULONG QueuedOutputReports;
    ULONG RingCapacity;
} CODEX_DRIVER_STATS, *PCODEX_DRIVER_STATS;

#pragma pack(pop)
